# GET: /health
GET http://localhost:3004/health

###
GET http://localhost:3004/auth/google
Content-Type: application/json

{
  "email": "emzzyoluwole@gmail.com"
}

### 
GET http://localhost:3004/emails
# Authorization: Bearer _Bearer Token_

### 
GET http://localhost:3004/auth/google

###
GET http://localhost:3004/emails

###

POST  http://localhost:3004/emails/cleanup
Content-Type: application/json

### Test Route for vetting prisma
GET http://localhost:3004/db-test